#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
